---
- name: create jenkins pipeline job
  hosts: Jenkins-Server
  tasks:
  - name: Jenkins pipeline job creation.
    jenkins_job:
       config: "{{ lookup('file', 'templates/config.xml') }}"
       name: Ansible-Jenkins-Pipeline-Job
       user: <Jenkins Username>
       password: <Jenkins Password>
       url: <Jenkins URL>

