---
- name: delete jenkins pipeline job
  hosts: Jenkins-Server
  tasks:
  - name: Jenkins pipeline job deletion.
    jenkins_job:
       name: Ansible-Jenkins-Pipeline-Job
       user: <Jenkins Username>
       state: absent
       password: <Jenkins Password>
       url: <Jenkins URL>

