---
- name: delete jenkins pipeline job using API auth token
  hosts: Jenkins-Server
  tasks:
  - name: delete Jenkins pipeline job.
    jenkins_job:
       name: Ansible-Jenkins-Pipeline-Job
       user: "{{ lookup('env','JENKINS_USER') }}"
       token: "{{ lookup('env','JENKINS_AUTH_TOKEN') }}"
       url: "{{ lookup('env','JENKINS_URL') }}"
       state: absent
