---
- name: disable jenkins pipeline job.
  hosts: Jenkins-Server
  tasks:
  - name: Disable Jenkins pipeline job.
    jenkins_job:
       name: Ansible-Jenkins-Pipeline-Job
       user: <Jenkins Username>
       password: <Jenkins Password>
       url: <Jenkins URL>
       enabled: no
