---
- name: enable jenkins plugin
  hosts: Jenkins-Server
  tasks:
  - name: enabled installed jenkins plugin 
    jenkins_plugin:
        name: CCM
        state: enabled
        url: "{{ lookup('env','JENKINS_URL')}}"
        url_username: "{{ lookup('env','JENKINS_USER')}}"
        url_password: "{{ lookup('env','JENKINS_PASSWORD')}}"

