---
- name: jenkins job info.
  hosts: Jenkins-Server
  tasks:
  - name: jenkins pipeline job info.
    jenkins_job_facts:
        color: blue
        user: "{{ lookup('env','JENKINS_USER') }}"
        password: "{{ lookup('env','JENKINS_PASSWORD') }}"
        url: "{{ lookup('env','JENKINS_URL') }}"
       
